### ISSUE TITLE
How to enable script to run in chrome for android?

### ISSUE THREAD

**Issue by dkapexhiu** [genielabs/zuix-web-template#1]
Firstly in desktop, adblocker blocked the script from loading the page. 
Now in mobile, chrome for android it is not possible to load the content of the page. 
How can i fix that?

**Comment by genemars** [comment]
If you have a public link to the project/page I can check it out.

**Comment by dkapexhiu** [comment]
Sorry it was a misconfiguration of config file in my project. Now it works!
Thanks!
